### ISSUE TITLE
Skipping ffprobe check for none image based representation 

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/ayon-ftrack#66]
# Current state
In `IntegrateFtrackInstance` plug-in the FFPROBE check is performed even on extensions which are not image based (ex. ABC, BLEND).

# Solution
An exclusion should be added so those representations are skipped for such a check.

# Publisher output
```
DEBUG: Getting information about input "P:\2023\AyonTests\assets\props\crate_a\publish\model\modelMain\v003\atst_crate_a_modelMain_v003.blend".
DEBUG: FFprobe command: "C:\Users\PIPELINE WORKSTATION\AppData\Local\Ynput\AYON\addons\ayon_third_party_1.0.0\ayon_third_party\downloads\ffmpeg\bin\ffprobe.exe" -hide_banner -loglevel fatal -show_error -show_format -show_streams -show_programs -show_chapters -show_private_data -print_format json P:\2023\AyonTests\assets\props\crate_a\publish\model\modelMain\v003\atst_crate_a_modelMain_v003.blend
DEBUG: FFprobe stdout:
{
    "error": {
        "code": -1094995529,
        "string": "Invalid data found when processing input"
    }
}

DEBUG: Failed to retrieve information about input P:\2023\AyonTests\assets\props\crate_a\publish\model\modelMain\v003\atst_crate_a_modelMain_v003.blend
```

**Comment by BigRoy** [comment]
Yes, please!

Having this exclusion or the ffprobe skipped for the publish file formats speeds up publishing, a lot because the running `ffprobe` is relatively slow - so it avoids quite some time spent processing something we know will fail anyway.

We've had this [hacky workaround in OpenPype for a long time](https://github.com/BigRoy/OpenPype/blob/dc27a9e608688657b726157b4ec633b33407506a/openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py#L550-L556) due to that.

But likely we're better of checking the extension is in `openpype.lib.transcoding.IMAGE_EXTENSIONS`?
